### ISSUE TITLE
Modernizr

### ISSUE THREAD

**Issue by jt3k** [slikts/tooling#6]
Please explain how you replace the Modernizr with `@babel/preset-env`

Do the creators of Modernizr know that they are not recommended? =)

**Comment by slikts** [comment]
The preferred alternative to feature detection is polyfilling, and `@babel/preset-env` is the simplest way to polyfill. Modernizr hasn't been relevant for a long time.

**Comment by jt3k** [comment]
are you really sure that `@babel/preset-env` can detect mix-blend-mode or cssgrid support and provide this information inside my css file?

**Comment by rejas** [comment]
I agree with @jt3k Modernizr still has some features that cant just be transpiled or polyfilled.

**Comment by slikts** [comment]
The legacy browser market share keeps shrinking, so the complexity of having branching logic based on feature detection for legacy browsers is increasingly not justified. The idea is to have recommendations for general use cases, and in general polyfilling should be preferred, even though it doesn't replace feature detection for every use case.

Here's [a graph](https://trends.google.com/trends/explore?date=all&q=modernizr,polyfill) that tells the same story; specifically, that Modernizr hit its peak when the legacy browser presence was much more significant.

**Comment by jt3k** [comment]
I see that both searches are popular in my country(Russia). But in the end, it's up to you.
Let’s at least add under the paragraph with modernizr why it is not recommended, and make a link to this issue

**Comment by slikts** [comment]
The trend looks [about the same](https://trends.google.com/trends/explore?date=all&geo=RU&q=modernizr,polyfill) in Russia. I've [added](https://github.com/slikts/tooling/commit/ff130d1ffafce93e2b2d84f6334a72c1e4071997) a link to this discussion.
